name: Publish nuget package

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Package Version (major.minor.patch)'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Pack
      run: dotnet pack -c Release -o out -p:PackageVersion=${{ github.event.inputs.version }}
    - name: PushNuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.PUBLISH_TO_NUGET_ORG}} --skip-duplicate
