name: Publish nuget package

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Package Version (major.minor.patch)'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet pack -c Release -o out -p:PackageVersion=${{ github.event.inputs.version }}
